name: recipe_finder

packages:
  - modules/*

command:
  version:
    branch: develop
    releaseUrl: true

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  get:
    exec: flutter pub get
  gen:
    exec: flutter pub run build_runner build --delete-conflicting-outputs