name: recipe_finder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.3'

dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection
  get_it: ^7.2.0
  injectable:
    path: ./../injectable/injectable

  # MODULES
  core:
    path: modules/core
  domain:
    path: modules/domain
  data:
    path: modules/data

  route_information:
    path: modules/common/route_information

  favourite_recipes:
    path: ./modules/features/favourite_recipes

  home:
    path: ./modules/features/home

  recipe_detail:
    path: ./modules/features/recipe_detail

  route_not_found:
    path: ./modules/features/route_not_found


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator:
    path: ./../injectable/injectable_generator
  melos: ^3.1.0

flutter:
  uses-material-design: true
