name: recipe_finder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # JSON Annotation Package
  json_annotation: ^4.8.0
  # Provider Inherited Widget Declaration
  provider: ^6.0.5
  # Adding gaps inside
  gap: ^3.0.0
  # Image Caching
  cached_network_image: ^3.2.3
  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.1

  # MODULES
  core:
    path: modules/core
  domain:
    path: modules/domain
  data:
    path: modules/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.5

flutter:
  uses-material-design: true
