name: presentation
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Provider Inherited Widget Declaration
  provider: ^6.0.5
  # Image Caching
  cached_network_image: ^3.2.3
  # Dependency Injection
  injectable: ^2.1.1
  # Adding gaps inside
  gap: ^3.0.0

  core:
    path: ../core

  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5