name: core

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^3.0.6
  flutter:
    sdk: flutter
  # Provider Inherited Widget Declaration
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0