name: core
version: 0.0.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.3'

dependencies:
  connectivity_plus: ^3.0.6
  flutter:
    sdk: flutter
  # Provider Inherited Widget Declaration
  provider: ^6.0.5
  # Dependency Injection
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0