name: recipe_detail
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Dependency Injection
  injectable: ^2.2.0
  # Adding gaps inside
  gap: ^3.0.0

  core:
    path: ../../core

  domain:
    path: ../../domain

  ui:
    path: ../../common/ui

  route_information:
    path: ../../common/route_information

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.3.0